import os
from dotenv import load_dotenv
from projects.keyvault_load import *
load_keyvault_secrets()

load_dotenv()
AZURE_CONN_STRING = os.getenv("azure-conn-string")
DB_NAME_IMG = os.getenv("cosmos-db-image")
CONT_NAME_IMG = os.getenv("cosmos-cont-image")
CHUNK_SIZE = int(os.getenv("chunk-size"))
CHUNK_OVERLAP = int(os.getenv("chunk-overlap"))
TOP_K = int(os.getenv("lt-top-k"))
EMBED_DIM = int(os.getenv("embed-dim"))
VECTOR_PATH = os.getenv("vector-path")
BLOB_CONTAINER_NAME = os.getenv("blob-container")
conn_str = os.getenv("azure-conn-string")
IMAGE_EXTS = os.getenv("lt-image-exts")
AOAI_ENDPOINT = os.getenv("aoai-endpoint")
AOAI_KEY = os.getenv("aoai-key")
API_VERSION = os.getenv("api-version")
EMBED_DEPLOY = os.getenv("embed-deploy")
CHAT_DEPLOY = os.getenv("chat-deploy")
COSMOS_URL = os.getenv("cosmos-url")
COSMOS_KEY = os.getenv("cosmos-key")
COSMOS_DB = os.getenv("cosmos-db-text")
COSMOS_CONT = os.getenv("cosmos-cont-text")
CONT_NAME = os.getenv("cosmos-cont-text")
DB_NAME = os.getenv("cosmos-db-text")
MAX_THREADS = int(os.getenv("lt-max-threads"))
MAX_RETRIES = int(os.getenv("lt-top-k"))
INITIAL_BACKOFF = int(os.getenv("lt-initial-backoff"))