import os
from dotenv import load_dotenv
load_dotenv()
AZURE_CONN_STRING = os.getenv("AZURE_CONN_STRING")
DB_NAME_IMG = os.getenv("COSMOS_DB_IMAGE")
CONT_NAME_IMG = os.getenv("COSMOS_CONT_IMAGE")
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE"))
CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP"))
TOP_K = int(os.getenv("LT_TOP_K"))
EMBED_DIM = int(os.getenv("EMBED_DIM"))
VECTOR_PATH = os.getenv("VECTOR_PATH")
BLOB_CONTAINER_NAME = os.getenv("BLOB_CONTAINER")
conn_str = os.getenv("AZURE_CONN_STRING")
IMAGE_EXTS = os.getenv("LT_IMAGE_EXTS")
AOAI_ENDPOINT = os.getenv("AOAI_ENDPOINT")
AOAI_KEY = os.getenv("AOAI_KEY")
API_VERSION = os.getenv("API_VERSION")
EMBED_DEPLOY = os.getenv("EMBED_DEPLOY")
CHAT_DEPLOY = os.getenv("CHAT_DEPLOY")
COSMOS_URL = os.getenv("LT_COSMOS_URL")
COSMOS_KEY = os.getenv("LT_COSMOS_KEY")
COSMOS_DB = os.getenv("COSMOS_DB_TEXT")
COSMOS_CONT = os.getenv("COSMOS_CONT_TEXT")
DB_NAME = os.getenv("COSMOS_DB_TEXT")
CONT_NAME = os.getenv("COSMOS_CONT_TEXT")
MAX_THREADS = int(os.getenv("LT_MAX_THREADS"))
MAX_RETRIES = int(os.getenv("LT_TOP_K"))
INITIAL_BACKOFF = int(os.getenv("LT_INITIAL_BACKOFF"))